---
- name: Start frontend server
  hosts:
    - frontend
  vars:
    java_home: "{{ websearch_home }}/jdk1.7.0_11"
    tomcat_home: "{{ websearch_home }}/tomcat-{{ socket }}"
    tomcat_http_port: "{{ 8080 + socket }}"
  tasks:
  - name: Remove log file
    file:
      path: "{{ tomcat_home }}/logs/catalina.out"
      state: absent
  - name: Start tomcat
    shell: "numactl --cpunodebind={{ socket }} {{ tomcat_home }}/bin/startup.sh"
    environment:
      JAVA_HOME: "{{ java_home }}"
    async: 10000 
    poll: 0
  - name: Wait for tomcat to start
    wait_for: port={{ tomcat_http_port }}