---
- name: Stop index server
  hosts:
    - index
  tasks:
  - name: Get the PID of running process
    ignore_errors: yes
    shell: "ps -few | grep -v grep | grep -w dis_search | awk '{print $2}'"
    register: running_processes
  - name: Kill running processes
    ignore_errors: yes
    shell: "kill {{ item }}"
    with_items: "{{ running_processes.stdout_lines }}"