---
- name: Start index server
  hosts:
    - index
  vars:
    java_home: "{{ websearch_home }}/jdk1.7.0_11"
  tasks:
  - include: partition.yml
  - name: Remove logs
    file:
      path: "{{ websearch_home }}/dis_search/logs/hadoop.log"
      state: absent
  - name: Configure number of threads
    xml:
      path: "{{ websearch_home }}/dis_search/conf/nutch-default.xml"
      xpath: /configuration/property[name="searcher.num.handlers"]/value
      value: "{{ index_server_threads_count | int }}"
  - name: Start index server
    shell: "{{ websearch_home }}/dis_search/bin/nutch search_server 8890 {{ partition_dir }}"
    environment:
      JAVA_HOME: "{{ java_home }}"
    async: 10000 
    poll: 0
  - name: Wait for index server to start
    wait_for: port=8890  