---
- name: Transfer and execute a script.
  hosts: all
  vars:
    PARTITION_BASE_DIR: "/local/websearch/test_out"
  tasks:
  # - name: Copy and Execute the script 
  #   script: mount_generate_index_part.sh
  - name: Assign partition 
    set_fact: 
      partition_id: "{{ groups['index'].index(inventory_hostname) }}"
      partition_count: "{{ groups['index'] | length }}"
      partition_path: "{{ PARTITION_BASE_DIR }}/{{ groups['index'] | length }}_{{ groups['index'].index(inventory_hostname) }}"
  - name: print id
    debug:
      msg: "{{ partition_path }}"
  - name: Create directory
    file:
      path: "{{ partition_path }}"
      state: directory
  - name: Mount tmpfs
    mount:
      path: "{{ partition_path }}"
      src: "tmpfs"
      fstype: tmpfs
      opts: size=8GB,mpol=bind:0
      state: present
    become: yes
